# Generated by Django 4.2.29 on 2026-04-04 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('training', 'Training'), ('offline', 'Offline')], default='active', max_length=20)),
                ('local_samples', models.IntegerField(default=0)),
                ('local_accuracy', models.FloatField(default=0.0)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FederatedRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True)),
                ('global_accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('participating_clients', models.IntegerField(default=0)),
                ('aggregation_time', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rounds', models.IntegerField(default=10)),
                ('current_round', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.TextField(blank=True)),
                ('participating_clients', models.ManyToManyField(blank=True, to='core.clientnode')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('true_positives', models.IntegerField(default=0)),
                ('true_negatives', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
                ('false_negatives', models.IntegerField(default=0)),
                ('confusion_matrix', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('federated_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='core.federatedround')),
            ],
        ),
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('DoS', 'Denial of Service'), ('Port Scan', 'Port Scan'), ('Brute Force', 'Brute Force'), ('Botnet', 'Botnet'), ('Normal', 'Normal Traffic'), ('SQL Injection', 'SQL Injection'), ('XSS', 'Cross-Site Scripting')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('probability', models.FloatField(default=0.0)),
                ('source_ip', models.CharField(blank=True, max_length=50)),
                ('destination_ip', models.CharField(blank=True, max_length=50)),
                ('protocol', models.CharField(blank=True, max_length=20)),
                ('bytes_transferred', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_features', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_logs', to='core.clientnode')),
                ('federated_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.federatedround')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
